POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXNpdG91MTYiLCJpZCI6IjY3OTFjMmQ5YzUzOTFjMjk0ZjdlMDYzYSIsImlhdCI6MTczNzY0NTk4MywiZXhwIjoxNzM3NjQ5NTgzfQ.WxP2m7gM1McfgJ1XCr19FkFU5dYyhqWn2qYy6jeTaHk
// alesitou16

{
  "title": "Successful blog",
  "author": "Alejandro Diaz Crivelli",
  "url": "https://github.com/diazale16",
  "likes": 16112001
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NzkxNzU4N2JkNjAyNmExYWY0ZTVjZGYiLCJpYXQiOjE3Mzc2NDU4NjQsImV4cCI6MTczNzY0OTQ2NH0.FzMrEyAD1pBriv5130RwMxMFfIGrscBKpN0-3is0VX8
// admin

{
  "title": "Authorized blog",
  "author": "Welix Wiaz Wrivelli",
  "url": "https://weeeeelix.com"
}
